### ISSUE TITLE
[iOS|Wasm][BottomBarNavigation] each visit to the sample page adds a new set of bar items

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/Uno.Material#153]
## Current behavior
Each visit to the sample page adds a new set of bar items.

## Expected behavior
Should not happen.

## How to reproduce it (as minimally and precisely as possible)
1. navigate to: BottomBarNavigation
2. navigate to: any other page
3. navigate to: BottomBarNavigation
4. repeat steps 2-3 for increasingly worse results
![image](https://user-images.githubusercontent.com/2359550/84177191-842f0100-aa50-11ea-95a5-e183b08d50ea.png)
![image](https://user-images.githubusercontent.com/2359550/84177207-8abd7880-aa50-11ea-86be-fc23026a6c68.png)
![image](https://user-images.githubusercontent.com/2359550/84177225-91e48680-aa50-11ea-9ad4-f5804b51ceeb.png)
![image](https://user-images.githubusercontent.com/2359550/84177463-e7209800-aa50-11ea-8da0-64306794679d.png)

## Environment

Nuget Package: Uno.UI
Package Version(s): 3.0.0-feature.styles-compat.216
Affected platform(s):

- [x] iOS
- [ ] Android
  > Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'
- [x] WebAssembly
- [ ] UWP
  > System.Exception: 'No installed components were detected. Element is already the child of another element.')
- [ ] MacOS

**Comment by Xiaoy312** [comment]
```cs
new PropertyMetadata(new List<BottomNavigationBarItem>(), OnItemsChanged));
```
All instance of this `BottomNavigationBar` reuses this list as default value...
\---
In wpf, we would have to set a new list in the .ctor: https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/collection-type-dependency-properties
However, it straight up crashes in uwp:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Cannot create instance of type 'Uno.Material.Controls.BottomNavigationBar' [Line: 16 Position: 52]
    at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
    at Uno.Material.Samples.Content.Controls.BottomNaviga
```

If we left the default value as null in the `PropertyMetadata`, it too crashes:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Collection property 'Uno.Material.Controls.BottomNavigationBar.Items' is null. [Line: 22 Position: 46]
    at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
    at Uno.Material.Samples.Content.Controls.BottomNa
```
\---
Based on this stackoverflow answer [here](https://stackoverflow.com/a/52455710) using `CreateDefaultValueCallback`, it doesnt crash, but the items is always empty...

**Comment by Xiaoy312** [comment]
@MatFillion 
We might have to re-implement this by sub-classing from ItemsControl or ListView(Base)?
Or, we could re-use existing control, like [`Pivot`](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/pivot), that has similar functionality and just re-skin them.
